const express = require('express')
const router = express.Router()

const authRoutes = require('./auth')
const propertiesRoutes = require('./properties')
const tenantsRoutes = require('./tenants')
const rentPaymentsRoutes = require('./rentPayments')
const maintenanceRoutes = require('./maintenance')
const cropsRoutes = require('./crops')
const harvestsRoutes = require('./harvests')
const buyersRoutes = require('./buyers')
const ordersRoutes = require('./orders')
const farmExpensesRoutes = require('./farmExpenses')
const financeRoutes = require('./finance')
const aiRoutes = require('./ai')
const notificationsRoutes = require('./notifications')
const settingsRoutes = require('./settings')
const marketPricesRoutes = require('./marketPrices')
const certificationsRoutes = require('./certifications')
const weatherRoutes = require('./weather')
const reExpensesRoutes = require('./reExpenses')

router.use('/auth', authRoutes)
router.use('/properties', propertiesRoutes)
router.use('/tenants', tenantsRoutes)
router.use('/rent-payments', rentPaymentsRoutes)
router.use('/maintenance', maintenanceRoutes)
router.use('/real-estate-expenses', reExpensesRoutes)
router.use('/crops', cropsRoutes)
router.use('/harvests', harvestsRoutes)
router.use('/buyers', buyersRoutes)
router.use('/orders', ordersRoutes)
router.use('/farm-expenses', farmExpensesRoutes)
router.use('/finance', financeRoutes)
router.use('/ai', aiRoutes)
router.use('/notifications', notificationsRoutes)
router.use('/settings', settingsRoutes)
router.use('/market-prices', marketPricesRoutes)
router.use('/certifications', certificationsRoutes)
router.use('/weather', weatherRoutes)

module.exports = router
